import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import ContactNavbar from "@/components/ContactNavbar";
import MainNavbar from "@/components/MainNavbar";
import Footer from "@/components/Footer";
import ReferralModal from "@/components/ReferralModal";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Refer and Earn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.variable} h-full`}>
        <ReferralModal />
        <ContactNavbar />
        <MainNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
